version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  nest-app:
    build:
      context: . # Build from the current directory
      dockerfile: Dockerfile
    container_name: mon-nest
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
            - dist/
            - model/
        - action: rebuild
          path: package.json
    ports:
      - '3000:3000'
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local
